### ISSUE TITLE
pam_radius_port

### ISSUE THREAD

**Issue by asifiqbal** [rji/puppet-pam_radius_auth#2]
Please add pam_radius_port as an option

templates/pam_radius.conf.erb
....
# server[:port] shared_secret      timeout (s)
<% @pam_radius_servers.each do |pam_radius_server| -%>
<%= pam_radius_server %>:<%= @pam_radius_port %>  <%= @pam_radius_secret %>  <%= @pam_radius_timeout %>
<% end -%>

manifests/init.pp
class pam_radius_auth($pam_radius_servers = [ "192.168.10.8",
                      "192.168.10.9" ],
                      $pam_radius_secret  = "secret",
                      $pam_radius_port  = '1812',
                      $pam_radius_timeout = '3' )

**Comment by rji** [comment]
Please see #1. Using Augeas is a better approach since it won't overwrite the entire file.
